### ISSUE TITLE
Prepare to move the repo into ministryofjustice for better maintainability

### ISSUE THREAD

**Issue by colinbruce** [colinbruce/laa-apply-bot#146]
TODO
===

- [x] Move to service accounts for kubectl work
- [x] Remove requirement to deploy locally
- [x] Address redis update/deploy
- [x] Update README
- [x] Create ECR image cleanup workflow
- [x] Switch to `main` as a branch name
